blank_issues_enabled: false
contact_links:
  - name: Theme Request
    url: https://github.com/node-red-contrib-themes/theme-collection/discussions/new?category=theme-request
    about: Suggest a new theme
