blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/node-red-contrib-themes/theme-collection/discussions/new?category=general
    about: Ask your question in the Discussions section
