---
name: "NPM Publish"

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  npm-publish:
    name: "Publish package to NPM"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Setup Node
        uses: actions/setup-node@v3.3.0
        with:
          node-version: "14"

      - name: Publish to npm (master branch)
        if: github.ref == 'refs/heads/master'
        uses: JS-DevTools/npm-publish@v1.4.3
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm (dev branch)
        if: github.ref == 'refs/heads/dev'
        uses: JS-DevTools/npm-publish@v1.4.3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: "next"
